# Generated by Django 3.2.5 on 2022-05-30 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220525_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='Imyarek', max_length=25, validators=[django.core.validators.RegexValidator(message='Please, enter the valid phone number', regex='^\\+\\d{11}$|^8\\d{10}$|^\\(\\d{3}\\)\\d{7}$|^\\(\\d{3}\\)\\d{3}\\-\\d{2}\\-\\d{2}$')]),
            preserve_default=False,
        ),
    ]
