# Generated by Django 3.2.5 on 2022-05-30 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220530_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Please, enter the valid phone number', regex='^\\+\\d{11}$|^8\\d{10}$|^\\(\\d{3}\\)\\d{7}$|^\\(\\d{3}\\)\\d{3}\\-\\d{2}\\-\\d{2}$')], verbose_name='Phone Number'),
        ),
    ]
