# Generated by Django 3.2.5 on 2022-06-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_customerbonuses_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuses',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
            preserve_default=False,
        ),
    ]
