# Generated by Django 3.2.5 on 2022-06-05 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_bonuses_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuses',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
