# Generated by Django 3.2.5 on 2022-06-15 19:19

from django.db import migrations, models
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220605_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=25, validators=[shop.utils.phone_validator], verbose_name='Phone Number'),
        ),
    ]
